---
title: "Chapter 16 Options on Stock Indices and Currencies"
output: html_document
---

## Options on stock indices

One index option contract is 100 times the index.

## Options on stocks paying known dividend yield

The payment of a dividend yield at rate $q$ means

* With a dividend yield $q$, the stock price grows from $S_0$ today to $S_T$ at time $T$.
* In the absence of dividends, it would grow from $S_0$ today to $S_Te^{qT}$ at time $T$.
* In the absence of dividends, it would grow from $S_0 e^{-qT}$ to $S_T$ at time $T$.

This leads to a simple rule

> When valuing a European option lasting for time $T$ on a stock paying a known dividend at rate $q$, we reduce the current stock price from $S_0$ to $Se^{-qT}$ and then value the oprion as though the stock pays on dividends.

In a risk-neutral world, the total return from the stock must be $r$. The dividends provide a return of $q$. Thus, the expected growth rate in the stock price is $r-q$. It follows
$$
dS = (r-q)Sdt + \sigma S dz
$$
The Black-Scholes equation becomes
$$
\dfrac{\partial f}{\partial t} + (r-q)S\dfrac{\partial f}{\partial S} + \frac{1}{2}\sigma^2S^2\dfrac{\partial^2 f}{\partial S^2} = rf
$$

----------------------------------------

Chapter 17 Futures Options
==========================

* *Spot option* : When the oprions are exercised, the sale of purchase of the asset at the agreed-on price takes place immediately.
* *Futures option* : The exercise of the option gives the holder a position in a futures contract.
    - If a *call futures option* is exercised, the holder acquires a long position in the underlying futures contract plus a cash amount equal to the most recent settlement futures price $F_T$ minus the strike price $K$. So the effective payoff is $$\max(F_T - K, 0)$$
    - For a *put futures option*, the payoff is $$\max(K - F_T, 0)$$

## Put-call parity

* *Portfolio A*: a European call futures option + cash equal to $Ke^{-rT}$
* *Portfolio B*: a European put futures option + a long futures contract + cash equal to $F_0 e^{-rT}$

where $F_0$ is the futures price.

The value at time $T$

* *Portfolio A*: $\max(F_T, K)$
* *Portfolio B*: $F_0 + (F_T - F_0) + \max(K-F_T, 0) = \max(F_T, K)$

The put-call parity is
$$
c + K e^{-rT} = p + F_0 e^{-rT}
$$
It is analoguous with the non-divident paying stock equation, only $S_0$ is replaced by the discounted futures price $F_0 e^{-rT}$. The futures price behaves like a stock providing a dividend yield $q$ equal to $r$. Thus with
$dF = \sigma F dz$, we have the differential equation for the forward contract
$$
\dfrac{\partial f}{\partial t} + \frac{1}{2}\sigma^2F^2\dfrac{\partial^2 f}{\partial F^2} = rf
$$












