---
title: "Interest Rates"
output: html_document
---

Two important interest rates for derivative traders are *Treasury rates* and *LIBOR rates*, they are both assumed as risk-free rate.

* *Treasury rates* are the rates paid by a government on borrowings in its own currency. 
* *LIBOR rates* are short-term lending rates offered by bancks in the interbank market.
  _LIBOR_ is short for _London Interbank Offered Rate_.

## Measuring interest rates

Suppose that an amount $A$ is invested for $n$ years at an interest rate of $R$ per annum. If the rate is *compounded* once per annum, the terminal value of the investment is $$A(1+R)^n$$

If the rate is compounded $m$ times per annum, the terminal value of the investment is $$A(1+ \dfrac{R}{m})^{mn}$$

When $m = 1$, the rate is sometimes referred to as *equivalent annual interest rate*.

When the compounding frequency $m \rightarrow \inf$, the limit is known as *continuous compounding*
$$
\lim_{m \rightarrow \inf} A(1+ \dfrac{R}{m})^{mn} = Ae^{Rn}
$$

For most practical purposes, continuous compounding can be thought of as being quivalent to daily compounding.

Suppose that 

* $R_c$ is a rate of interest with continuous compounding 
* $R_m$ is the equivalent rate with compounding $m$ times per annum. 

We can convert one to the other with
$$
Ae^{R_c n} = A(1+ \dfrac{R_m}{m})^{mn} \Rightarrow e^{R_c} = (1+ \dfrac{R_m}{m})^m
$$
Thus
$$
R_c = m \ln(1+ \dfrac{R_m}{m}) \qquad R_m = m(e^{R_c/m} - 1)
$$

**Def.** The n-year *zero-coupon rate* (also known as n-year *spot rate* or n-year *zero rate*) is the rate of interest earned on an investment that starts today and lasts for n years. All the interest and principal is realized at the end of n years, there is no intermediate payments.

*Example.* A 5-year zero rate with continuous compounding is quoted as 5% per annum, this means that $100 if invested for 5 years, will grow to $100 \times e^{0.05\times 5} =$ `r 100 * exp(0.05*5)` 

While most of the interest rates in the market are not directly pure zero rates, for example when it includes coupon.

--------------------------

## Bonds Pricing

Most bounds pay coupons to the holder periodically. The bond's principal (which is also known as is *par value* or *face value*) is paid at the end of its life.

*The theoretical price* of a bond = the present value of all the cash flows that will be received by the owner, it is also known as the *bond price*.

A *bond yield* is the single discount rate that, when applied to all cash flows, gives a bond price equal to its market price.

The *par yield* for a certain bond maturity is the coupon rate that causes the bond price to equal its par value.

-------------------

## Forward Rates

*Forward interest rates* are the rates of interest implied by current zero rates for periods of time in the future.

Suppose $R_1$ and $R_2$ the zero rats for maturities $T_1$ and $T_2$ respectively and $R_F$ the forward interest rate for the period between $T_1$ and $T_2$, then
$$
R_F = \dfrac{R_2 T_2 - R_1 T_1}{T_2 - T_1}
$$
Thus
$$
R_F = R_2 + T_1 \dfrac{R_2 - R_1}{T_2 - T_1}
$$

When $T_2 \rightarrow T_1$, we obtain $R_F = R + T \dfrac{\partial R}{\partial T}$, where $R$ is the zero rate for a maturity of $T$. The value of $R_F$ is known as the *instantaneous forward rate* for a maturity $T$. This is the forward rate that is applicable to a very short future time period that begins at time $T$.

Define $P(0,T)$ as the price of a zero-coupon bond maturing at time $T$. Because $P(0,T) = e^{-RT}$, we have
$$
R_F = -\dfrac{\partial}{\partial T} \ln P(0,T)
$$

### Forward rate agreement

A *forward rate agreement (FRA)* is an over-the-counter agreement that a certain interest rate will apply to either borrowing or lending a certain principal during a specified future period of time.

Consider a forward rate agreement where company X is agreeing to lend money to company Y for the period of time between $T_1$ and $T_2$. Define

* $R_K$ : The rate of interest agreed to in the FRA (It is usually the case that $R_K$ is set equal to $R_F$ when the FRA is first initiated.)
* $R_F$ : The forward LIBOR interest rate for the period between times $T_1$ and $T_2$, calculated today.
* $R_M$ : The actual LIBOR interest rate observed in the market at time $T_1$ for the period between times $T_1$ and $T_2$
* $L$ : The principal underlying the contract

### Duration

The *duration* of a bond is a measure of how long on average the holder of the bond has to wait before receiving cash payments. It is in fact a weighted average of the times when payments are made, with the weight applied to time $t_i$ being equal to the proportion of the bond's total present value provided by the cash flow at time $t_i$
$$
D := \sum_{i=1}^{n} t_i [\dfrac{c_i e^{-y t_i}}{B}] \qquad where \quad B = \sum_{i=1}^{n} c_i e^{-y t_i}
$$

Consider a small change in the bond yield $\Delta y$, we have approximately $\Delta B = \dfrac{dB}{dy} \Delta y$, thus
$$
\Delta B = - \Delta y \sum_{i=1}^{n} c_i t_i e^{-y t_i} = - \Delta y BD
$$











