---
title: "Determination of Forward and Futures Prices"
output: html_document
---

**Def.** *investment asset* vs. *consumption asset*

a. An *investment asset* is an asset that is held for investment purposes by significant numbers of investors, such as stocks and bonds, gold and silver.
b. A *consumption asset* is an asset that is held primarily for consumption, such as copper, oil and pork bellies.

We can use arbitrage arguments to determine the forward and futures prices of an investment asset from its spot price and other observable market variables, but we cannot do this for consumption assets.

**Def.** *Short selling* is to sell something that is not owned. It is possible for some investment assets.

Short sales are not possible for all investment assets and sometimes a fee is charged for borrowing assets.

An investor with a short position must pay to the broker any income, such as dividends or interest, that would normally be received on the securitoes that have been shorted.

---------------------------------

## Forward Price for an Investment asset

**Notation.**

* $T$ : Time until delivery date in a forward of futures contract (in years)
* $S_0$ : Price of the asset underlying the forward or futures contract today
* $F_0$ : Forward or futures price today
* $r$ : Zero-coupon risk free rate of interest per annum, expressed with continuous compounding

First we know that the value of the asset at the time $T$ is $S_0 e^{rT}$

* If $F_0 > S_0 e^{rT}$, arbitrageurs can buy the asset and short forward contract with time $T$.
* If $F_0 < S_0 e^{rT}$, arbitrageurs can short the asset and long forward contract with time $T$ and invest the revenue for three month.

For there to be no arbitrage, the forward price must be $$F_0 = S_0 e^{rT}$$

If the forward price were less than this, an arbitrageur would short the stock and buy forward contracts. If the forward price were greater than this, he would short forward contracts and buy the stock in the spot market.

### Known income

Suppose that the investment asset will provide income with a present value $I$ during the life of a forward contract, then for there to be no arbitrage, whe must have $$F_0 = (S_0 - I) e^{rT}$$ 

### Known yield

We now consider the situation where the asset underlying a forward contract provides known yield $q$ rather than a known income. Then $$F_0 = S_0 e^{(r-q)T}$$

---------------------------------

## Valuing forward contracts

The value of a forward contract at the time when it is first entered into is zero. At a later stage, it may have a positive or negative value, it is important to value it each day. 

Suppose $K$ the delivery price for a contract that was negotiated some time ago, $F_0$ is the forward price that would be applicable if we negotiated the contract today. Define $f$ to be the value of forward contract today.

To be clear,

* At the time 0, $F_0 = K$ and the value of the contract $f = 0$
* At a later stage, $K$ stays the same but $F_0$ will change, so $f$ will also change

A general result applicable to all long forward contract is $$f = (F_0 - K)e^{-rT} = S_0 - K e^{-rT}$$

And the value of a short forward contract would be $$f = (K - F_0)e^{-rT} = K e^{-rT} - S_0$$

### Forward prices and futures prices

When a futures price changes, the gain or loss on a futures contract is calculated as the change in the futures price multiplied by the size of the position. The gain is realized almost **immediately** because futures contracts are settled daily.

When a forward price changes, the gain or loss is the preent value of the change in the **present value** multiplied by the size of the position.

---------------------------------

## Futures prices of stock indices

A stock index can usually be regarded as the price of an investment asset that pays dividends. The investment asset is the portfolio of stocks underlying the index, and the dividends that would be received by the holder of this portfolio.

It is usually assumed that the dividends provide a known yield rather than a known cash income. If $q$ is the dividend yield rate, the futures price $F_0$ should be
$$F_0 = S_0 e^{(r-q)T}$$

### Index Arbitrage

It is similar to futures arbitrage. Consider the two following cases

* $F_0 > S_0 e^{(r-q)T}$
* $F_0 < S_0 e^{(r-q)T}$

---------------------------------

## Forward and futures contracts on currencies

From the perspective of a US investor, the underlying asset is one unit of the foreign currency. Suppose

* $S_0$ the current spot price in USD of one unit of the foreign currency
* $F_0$ the forward or futures price in USD of one unit of the foreign currency

A foreign currency has the property that the holder of the currency can earn interest at the risk-free interest rate prevailing in the foreign country. We can define $r_f$ as the value of the foreign risk-free interest rate when money is invested for time $T$. The variable $r$ is the USD risk-free rate when money is invested for this period of time.

The relationship between $F_0$ and $S_0$ is
$$
F_0 = S_0 e^{(r-r_f)T}
$$
A foreign currency can also be regarded as an investment asset paying a known yield.

---------------------------------

## Futures on commodities

* *Income and storage costs*
* *Comsumption commodities*
* *Convenience yield* : The benefits from holding the physical asset. It reflects the market's expectations concerning the future availability of the commodity. The greater the possibility that shortages will occur, the higher the convenience yield.













